[install]
# Configura o comportamento de instalação do Bun
peer = true
production = false
optional = true
dev = true
exact = false

[install.scripts]
# Sempre executar install scripts (necessário para sharp, canvas, etc)
disable = false
allowList = ["*"]

[install.cache]
# Habilita cache de instalação
disable = false

[install.lockfile]
# Configurações do lockfile
save = true
print = "bun"

[run]
# Shell para executar scripts
shell = "system"
